Feature/swagger
Akatsuki-USW/Buzzzzing-Server pull request #42
Opened 2023-07-31 02:31 UTC by woo0doo

## PR 요약
User, Auth 등 swagger 추가 및 Async 추가

## 구현한 내용 또는 수정한 내용
메일 보내는 API 걸리는 시간

before
![image](https://github.com/Akatsuki-USW/Buzzzzing-Server/assets/114072164/372c6b29-1c5a-424b-86b8-c0e8a80d4457)

after
![image](https://github.com/Akatsuki-USW/Buzzzzing-Server/assets/114072164/8f6190fc-7930-4394-be3b-b483e5bdafc9)

엄청난 시간 최적화..

## 추가로 알리고 싶은 내용

## 관련 이슈

## 체크리스트

- [ ]  본인을 Assign해주시고, 본인을 제외한 백엔드 개발자를 Reviewer로 지정해주세요.
- [ ]  WBS 업데이트해주세요. (제목에 WBS 번호 달아주세요)
- [ ]  라벨 체크해주세요.
- [ ]  .yml 파일 수정 내용이 있다면 공유해주세요!

2023-07-31 04:34 UTC, wonslee requested changes
와우... Async 적용해서 성능 개선 이거 어필할만 하네요.
노션 `문제 발굴하기` 페이지에 정리 고고

2023-07-31 04:34 UTC, wonslee commented on src/main/java/bokjak/bokjakserver/config/AsyncConfig.java
> +    }
공부해봐야겠네요..!
sendPushMessage, sendMail 에서 이 Config대로 비동기 처리하는 흐름인건가요?

2023-07-31 04:34 UTC, wonslee commented on src/main/java/bokjak/bokjakserver/domain/user/controller/UserController.java
> +    @Operation(summary = USER_ME)
스웨거에서 authorize 기능 쓰려면 @SecurityRequirement 붙여줘야 합니다.
지금 상태에선 아마 스웨거에서 요청 못할거예유.
 #39 참고

2023-07-31 04:40 UTC, woo0doo commented on src/main/java/bokjak/bokjakserver/domain/user/controller/UserController.java
> +    @Operation(summary = USER_ME)
아하 참고하겠습니다!

2023-07-31 04:40 UTC, woo0doo commented on src/main/java/bokjak/bokjakserver/config/AsyncConfig.java
> +    }
맞습니다~

2023-07-31 04:40 UTC, woo0doo commented
하하 이미 살짝 적어놨지요

2023-07-31 04:43 UTC, wonslee commented
ㅋㅋㅋ 뭘요

2023-07-31 04:46 UTC, woo0doo commented
그 spring 공부에 간단하게 적어놨어요

2023-08-01 12:02 UTC, wonslee approved these changes
:+1: 스웨거 만족ㅎㅎ

2023-08-01 12:04 UTC, woo0doo commented on src/main/java/bokjak/bokjakserver/domain/notification/service/NotificationService.java
> +        );
저거 그 트랜잭션 에러뜹니다.. ㅎㅎ 서비스상에서 한번 더 조회해야 영속성 컨텍스트 안으로 들어옵니다! 저번에 같이 얘기한 부분입니다!

2023-08-01 13:39 UTC, wonslee commented on src/main/java/bokjak/bokjakserver/domain/notification/service/NotificationService.java
> +        );
아하 loginUser.getNotificationList() 에서 쓰이는군요 확인

2023-08-02 04:04 UTC, merged