fix: 혼잡도 일간 통계 9시 이후 데이터만 응답
Akatsuki-USW/Buzzzzing-Server pull request #63
Opened 2023-08-16 05:32 UTC by wonslee

## PR 요약
YMDHM 형식 유틸 추가

혼잡도 통계 DTO 수정
스팟, 댓글 상세 조회 DTO 수정

## 구현한 내용 또는 수정한 내용
혼잡도 일간 통계 9시 이후 데이터만 응답하도록 수정

스팟, 댓글 조회 DTO : 생성일자, 수정일자 -> YMDHM (yyyy-mm-dd HH:MM) 포맷으로 수정

## 추가로 알리고 싶은 내용

## 관련 이슈

## 체크리스트

- [x]  본인을 Assign해주시고, 본인을 제외한 백엔드 개발자를 Reviewer로 지정해주세요.
- [x]  WBS 업데이트해주세요. (제목에 WBS 번호 달아주세요)
- [x]  라벨 체크해주세요.
- [x]  .yml 파일 수정 내용이 있다면 공유해주세요!

2023-08-16 06:42 UTC, woo0doo requested changes

2023-08-16 06:42 UTC, woo0doo commented on src/main/java/bokjak/bokjakserver/util/CustomDateUtils.java
> +    public static String customDateFormatYMDHM(LocalDateTime localDateTime) {
흠 YMDHM보다 더 좋은 함수명이 없을까요?

2023-08-19 08:42 UTC, wonslee commented on src/main/java/bokjak/bokjakserver/util/CustomDateUtils.java
> +    public static String customDateFormatYMDHM(LocalDateTime localDateTime) {
제 센스로는 이게 한계입니다...
아니면 YYYYMMDDHHMM?

2023-08-19 08:42 UTC, wonslee commented on src/main/java/bokjak/bokjakserver/util/CustomDateUtils.java
> +    public static String customDateFormatYMDHM(LocalDateTime localDateTime) {
YearToMinute?

2023-08-19 08:52 UTC, wonslee commented on src/main/java/bokjak/bokjakserver/util/CustomDateUtils.java
> +    public static String customDateFormatYMDHM(LocalDateTime localDateTime) {
후후,.,,
 스프링에서 쓰는 공식 의존성에 이런 함수가 있네요?
![image](https://github.com/Akatsuki-USW/Buzzzzing-Server/assets/72124326/417b3c05-d0ac-4238-b4cb-6f2e8cc5c008)

2023-08-19 08:58 UTC, wonslee commented on src/main/java/bokjak/bokjakserver/util/CustomDateUtils.java
> +    public static String customDateFormatYMDHM(LocalDateTime localDateTime) {
아니면.. 파라미터로 LocalDateTime과 패턴 문자열을 받는 함수를 만들까요?

```
...customDateFormat(LocalDateTime localDateTime, String pattern){ 
    return localDateTime.format(DateTimeFormatter.ofPattern(pattern));
}
```

패턴 문자열들은 상수로 저장하구요! 
그러면 재사용성도 높아지고 코드도 깔끔해질거같기는 합니다

2023-08-20 08:09 UTC, woo0doo approved these changes

2023-08-20 08:09 UTC, woo0doo commented on src/main/java/bokjak/bokjakserver/util/CustomDateUtils.java
> +    public static String customDateFormatYMDHM(LocalDateTime localDateTime) {
오 깔끔합니다 !! 저거로 가시죠!!

2023-08-20 08:51 UTC, merged